# Generated by Django 6.0.6 on 2026-07-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified'),
        ('accounts', '0002_user_is_email_verified_emailotp'),
    ]

    operations = [
    ]
