# Generated by Django 5.2.15 on 2026-07-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_usertaskprogress_id'),
        ('dashboard', '0002_userprofile'),
    ]

    operations = [
    ]
