# Generated by Django 6.0.6 on 2026-07-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_usertaskprogress_id'),
        ('dashboard', '0002_userprofile'),
    ]

    operations = [
    ]
