# Generated by Django 6.0.6 on 2026-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_merge_0002_alter_usertaskprogress_id_0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
