# Generated by Django 6.0.6 on 2026-07-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_usertaskprogress_id'),
        ('dashboard', '0004_userprofile_current_field_and_more'),
    ]

    operations = [
    ]
