# Generated by Django 6.0.6 on 2026-06-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_transferable', models.BooleanField(default=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.skill')),
            ],
            options={
                'unique_together': {('career', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='career',
            name='required_skills',
            field=models.ManyToManyField(related_name='careers', through='careers.CareerSkill', to='careers.skill'),
        ),
    ]
