# Generated by Django 6.0.5 on 2026-07-06 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('estimated_time', models.CharField(default='6 Months', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_transferable', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=10)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill')),
            ],
            options={
                'unique_together': {('career', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='career',
            name='required_skills',
            field=models.ManyToManyField(related_name='careers', through='careers.CareerSkill', to='skills.skill'),
        ),
        migrations.CreateModel(
            name='SelectedCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_by', to='careers.career')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_career', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
