# Generated by Django 6.0.6 on 2026-07-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedCareer',
        ),
    ]
