# Generated by Django 5.2.15 on 2026-07-01 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_career_id_alter_careerskill_id_alter_skill_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCareer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_by', to='careers.career')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_career', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
