# Generated by Django 6.0.6 on 2026-07-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_remove_selectedcareer'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='icon',
            field=models.CharField(blank=True, default='💼', max_length=10),
        ),
    ]
