# Generated by Django 6.0.6 on 2026-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_career_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='icon_color',
            field=models.CharField(choices=[('default', 'Indigo'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('pink', 'Pink')], default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='career',
            name='icon',
            field=models.CharField(blank=True, default='bi-briefcase', max_length=30),
        ),
    ]
